In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import numpy.polynomial.polynomial as poly
import pandas as pd
%load_ext autoreload
%autoreload 2

In [5]:
from scripts.proj1_helpers import *
from implementations import *
from cross_validations import *

In [6]:
y, input_data, ids = load_csv_data('../../train_nojet.csv')
y_test, test_data, ids_test = load_csv_data('../../test.csv')

In [ ]:
def build_polya(x, degree):
    """ Apply a polynomial basis to all the X features. """
    # First, we find the combinations of columns for which we have to
    # compute the product
    m, n = x.shape

    combinations = {}

    # Add combinations of same column power
    for i in range(n * degree):
        if i < n:
            combinations[i] = [i]
        else:
            col_number = i - n
            cpt = 2
            while col_number >= n:
                col_number -= n
                cpt += 1
            combinations[i] = [col_number] * cpt

    # Add combinations of products between columns
    cpt = i + 1

    for i in range(n):
        for j in range(i + 1, n):
            combinations[cpt] = [i, j]
            cpt = cpt + 1

    # Now we can fill a new matrix with the column combinations
    eval_poly = np.zeros(
        shape=(m, n + len(combinations))
    )

    for i, c in combinations.items():
        eval_poly[:, i] = x[:, c].prod(1)

    # Add square root
    for i in range(0, n):
        eval_poly[:, len(combinations) + i] = np.abs(x[:, i]) ** 0.5

    return eval_poly

In [ ]:
from itertools import product
list(map(lambda x: x[0] * x[1], product([1,2,3], repeat=2)))

In [ ]:
po = build_poly(m,3)
outpo = np.empty([po[0].shape[0], po.shape[0]*po[0].shape[1]])
print(outpo.shape)
for i in range(po[0].shape[0]):
    
    outpo[i] = np.append(po[0, i], po[1, i]) 
outpo

In [19]:
def accuracy(original_data, approximation):
    return np.equal(original_data, approximation).sum()/float(len(approximation))

In [22]:
seed = 1
degree = 4
k_fold = 4
max_iters = 50
gamma = 0.7
# split data in k fold
k_indices = build_k_indices(y, k_fold, seed)

In [10]:
train = pd.read_csv('../../train.csv', index_col='Id', na_values=-999)


In [38]:
train

Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  \
Id                                                                           
100000          s       138.470                       51.655        97.827   
100001          b       160.937                       68.768       103.235   
100002          b           NaN                      162.172       125.953   
100003          b       143.905                       81.417        80.943   
100004          b       175.864                       16.915       134.805   
100005          b        89.744                       13.550        59.149   
100006          s       148.754                       28.862       107.782   
100007          s       154.916                       10.418        94.714   
100008          b       105.594                       50.559       100.989   
100009          s       128.053                       88.941        69.272   
100010          b           NaN                       86.240        79.692   
100011          b       114.744                       10.286        75.712   
100012          b       145.297                       64.234       103.565   
100013          b        82.488                       31.663        64.128   
100014          b           NaN                      109.412        14.398   
100015          s       111.026                       32.096        75.271   
100016          b       114.256                        4.351        67.963   
100017          s       127.861                       50.953        77.267   
100018          b           NaN                       85.186        68.827   
100019          b           NaN                       88.767       115.058   
100020          b           NaN                       89.705        41.765   
100021          b        90.736                       18.674        60.231   
100022          b        87.075                       38.217        67.041   
100023          s       141.481                        0.736       111.581   
100024          b       110.785                       72.927        82.775   
100025          b        76.883                       34.384        56.993   
100026          s       137.197                       68.009        78.296   
100027          s       111.271                       27.180        70.642   
100028          s       118.104                        2.633        77.310   
100029          b        98.761                       14.024        74.230   
...           ...           ...                          ...           ...   
349970          s       158.674                       80.380        75.571   
349971          b           NaN                      173.688        91.969   
349972          s       102.569                       53.660        69.926   
349973          b       103.483                        6.101        63.502   
349974          s       128.898                        2.446        92.990   
349975          s       140.352                       15.046        84.924   
349976          s       137.371                        4.640        92.603   
349977          b        96.952                       85.701        87.170   
349978          b        86.190                       17.227        60.069   
349979          b        92.645                        2.855        66.797   
349980          s       119.934                       20.078        88.751   
349981          b        87.390                        0.299        40.546   
349982          s       146.903                       83.727       104.591   
349983          b        80.388                       67.071        58.603   
349984          s       112.308                       30.722        73.178   
349985          s       126.151                       29.023        95.258   
349986          s       164.310                        1.535       115.781   
349987          b       140.080                       29.729        83.393   
349988          b        89.5

In [39]:
nojet = train.dropna(axis = 1, thresh=int(0.99*len(train)))

In [39]:
len(train.columns)

31

In [40]:
len(nojet.columns)

20

In [14]:
nojet.dtypes

Prediction                      object
DER_mass_transverse_met_lep    float64
DER_mass_vis                   float64
DER_pt_h                       float64
DER_deltar_tau_lep             float64
DER_pt_tot                     float64
DER_sum_pt                     float64
DER_pt_ratio_lep_tau           float64
DER_met_phi_centrality         float64
PRI_tau_pt                     float64
PRI_tau_eta                    float64
PRI_tau_phi                    float64
PRI_lep_pt                     float64
PRI_lep_eta                    float64
PRI_lep_phi                    float64
PRI_met                        float64
PRI_met_phi                    float64
PRI_met_sumet                  float64
PRI_jet_num                      int64
PRI_jet_all_pt                 float64
dtype: object

In [34]:
0.99*len(train)

247500.0

In [65]:
def normalize(df) :
    if df.name in ['Prediction', 'PRI_jet_num']:
        return df
    return (df - df.min()) / (df.max() - df.min())

In [71]:
normalized = train.fillna(0).apply(normalize, axis=0)

In [72]:
normalized.to_csv("../../train_nojet.csv")

In [73]:
normalized.head()

Prediction  DER_mass_MMC  DER_mass_transverse_met_lep  DER_mass_vis  \
Id                                                                           
100000          s      0.116164                     0.074854      0.068128   
100001          b      0.135011                     0.099653      0.072155   
100002          b      0.000000                     0.235006      0.089071   
100003          b      0.120723                     0.117983      0.055557   
100004          b      0.147534                     0.024512      0.095662   

        DER_pt_h  DER_deltaeta_jet_jet  DER_mass_jet_jet  DER_prodeta_jet_jet  \
Id                                                                              
100000  0.009869              0.107021          0.025068             0.596501   
100001  0.016983              0.000000          0.000000             0.519795   
100002  0.012570              0.000000          0.000000             0.519795   
100003  0.000146              0.000000          0.000000             0.519795   
100004  0.005787              0.000000          0.000000             0.519795   

        DER_deltar_tau_lep  DER_pt_tot       ...        PRI_met_phi  \
Id                                           ...                      
100000            0.521549    0.014789       ...           0.455920   
100001            0.596238    0.000733       ...           0.195099   
100002            0.536888    0.003293       ...           0.152132   
100003            0.566472    0.000146       ...           0.509548   
100004            0.672571    0.005787       ...           0.361394   

        PRI_met_sumet  PRI_jet_num  PRI_jet_leading_pt  PRI_jet_leading_eta  \
Id                                                                            
100000       0.123125            2            0.060179             0.738942   
100001       0.075802            1            0.041252             0.580573   
100002       0.123969            1            0.039490             0.728162   
100003       0.036368            0            0.000000             0.500000   
100004       0.019823            0            0.000000             0.500000   

        PRI_jet_leading_phi  PRI_jet_subleading_pt  PRI_jet_subleading_eta  \
Id                                                                           
100000             0.570746               0.063846                0.637778   
100001             0.684386               0.000000                0.500000   
100002             0.177304               0.000000                0.500000   
100003             0.500080               0.000000                0.500000   
100004             0.500080               0.000000                0.500000   

        PRI_jet_subleading_phi  PRI_jet_all_pt  
Id                                              
100000                0.106143        0.069484  
100001                0.500000        0.028300  
100002                0.500000        0.027091  
100003                0.500000        0.000000  
100004                0.500000        0.000000  

[5 rows x 31 columns]

In [70]:
normalized.columns

Index(['Prediction', 'DER_mass_transverse_met_lep', 'DER_mass_vis', 'DER_pt_h',
       'DER_deltar_tau_lep', 'DER_pt_tot', 'DER_sum_pt',
       'DER_pt_ratio_lep_tau', 'DER_met_phi_centrality', 'PRI_tau_pt',
       'PRI_tau_eta', 'PRI_tau_phi', 'PRI_lep_pt', 'PRI_lep_eta',
       'PRI_lep_phi', 'PRI_met', 'PRI_met_phi', 'PRI_met_sumet', 'PRI_jet_num',
       'PRI_jet_all_pt'],
      dtype='object')

In [9]:
a= np.array([[2,3,4,54,5], [2,6,8,1,4],[2,6,8,4,4]])
np.where(a[:,3]%2==0)

(array([0, 2]),)

In [11]:
train.columns

Index(['Prediction', 'DER_mass_MMC', 'DER_mass_transverse_met_lep',
       'DER_mass_vis', 'DER_pt_h', 'DER_deltaeta_jet_jet', 'DER_mass_jet_jet',
       'DER_prodeta_jet_jet', 'DER_deltar_tau_lep', 'DER_pt_tot', 'DER_sum_pt',
       'DER_pt_ratio_lep_tau', 'DER_met_phi_centrality',
       'DER_lep_eta_centrality', 'PRI_tau_pt', 'PRI_tau_eta', 'PRI_tau_phi',
       'PRI_lep_pt', 'PRI_lep_eta', 'PRI_lep_phi', 'PRI_met', 'PRI_met_phi',
       'PRI_met_sumet', 'PRI_jet_num', 'PRI_jet_leading_pt',
       'PRI_jet_leading_eta', 'PRI_jet_leading_phi', 'PRI_jet_subleading_pt',
       'PRI_jet_subleading_eta', 'PRI_jet_subleading_phi', 'PRI_jet_all_pt'],
      dtype='object')

In [9]:
find_param_jets(y, input_data)

Current iteration=0, loss=25141.141386089774, acc=0.644564528135425, gamma=0.1, lambda=0.001
-> new average acc: 0.6170960671601671
Current iteration=0, loss=25141.141386089774, acc=0.644564528135425, gamma=0.1, lambda=0.001
Current iteration=0, loss=25141.141386089774, acc=0.6446196686057732, gamma=0.1, lambda=0.01
0.701772766121695 | d: 4 | g: 0.1 | l: 0.01 | fold 0
Current iteration=0, loss=25141.141386089774, acc=0.6496925918778087, gamma=0.1, lambda=0.01
-> new average acc: 0.7081592986228857
Current iteration=0, loss=25141.141386089774, acc=0.6467701469493535, gamma=0.1, lambda=0.6
0.7056325990460699 | d: 4 | g: 0.1 | l: 0.6 | fold 0
Current iteration=0, loss=25141.141386089774, acc=0.6520084916324336, gamma=0.1, lambda=0.6
-> new average acc: 0.7202900348758667
Current iteration=0, loss=25141.141386089774, acc=0.6449229411926883, gamma=0.1, lambda=0.1
Current iteration=0, loss=25141.141386089774, acc=0.644564528135425, gamma=0.2, lambda=0.001
Current iteration=0, loss=25141.1413

Current iteration=0, loss=25141.141386089774, acc=0.634942516059662, gamma=0.6, lambda=0.01
Current iteration=0, loss=25141.141386089774, acc=0.6349149458244879, gamma=0.6, lambda=0.6
Current iteration=0, loss=25141.141386089774, acc=0.6348322351189656, gamma=0.6, lambda=0.1
Current iteration=0, loss=25141.141386089774, acc=0.634942516059662, gamma=0.7000000000000001, lambda=0.001
Current iteration=0, loss=25141.141386089774, acc=0.634942516059662, gamma=0.7000000000000001, lambda=0.001
Current iteration=0, loss=25141.141386089774, acc=0.634942516059662, gamma=0.7000000000000001, lambda=0.01
Current iteration=0, loss=25141.141386089774, acc=0.6348873755893137, gamma=0.7000000000000001, lambda=0.6
Current iteration=0, loss=25141.141386089774, acc=0.6348322351189656, gamma=0.7000000000000001, lambda=0.1
Current iteration=0, loss=25141.141386089774, acc=0.634942516059662, gamma=0.8, lambda=0.001
Current iteration=0, loss=25141.141386089774, acc=0.634942516059662, gamma=0.8, lambda=0.001
C

KeyboardInterrupt: 

In [12]:
a=np.array([1,2,3,4,5])
np.where(a%2==0)[0]

array([1, 3])

In [3]:
a=np.array([[1,2,3],[4,5,6]])
a[a==3]=2

In [4]:
a

array([[1, 2, 2],
       [4, 5, 6]])